// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWalletApi.Data;

namespace TestWalletApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWalletApi.Models.CurrencyTab", b =>
                {
                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.Property<int>("Сurrency")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("ChangeVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("WalletId", "Сurrency");

                    b.ToTable("CurrencyTabs");
                });

            modelBuilder.Entity("TestWalletApi.Models.IdempotentCache", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotentKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParametersHash")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "IdempotentKey", "ParametersHash");

                    b.ToTable("IdempotentCaches");
                });

            modelBuilder.Entity("TestWalletApi.Models.Wallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("TestWalletApi.Models.CurrencyTab", b =>
                {
                    b.HasOne("TestWalletApi.Models.Wallet", "Wallet")
                        .WithMany("CurrencyTabs")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
